### ISSUE TITLE
How to build quiche.so

### ISSUE THREAD

**Issue by LeonDestiny** [JBou/netty-quic-demo#2]
Hi JBou,
I'm looking forward to use Netty QUIC, but Netty says that they don't support Android platfrom.
But I found the Netty QUIC aar here.
I'm very eager to know how you packaged quiche's .so and integrated it into .aar.

(PS: The repo of 'quiche' i'm using is https://github.com/cloudflare/quiche, am I on the right repo?)

**Comment by LeonDestiny** [comment]
I successfully connect QUIC server by using your WONDERFUL quic-native-aar. 
I tried to type libquich.so according to the official website of quiche to replace quic-native-aar, but it failed().
Hope I can gain useful experience from you

```java
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for int io.netty.incubator.codec.quic.QuicheNativeStaticallyReferencedJniMethods.afInet() (tried Java_io_netty_incubator_codec_quic_QuicheNativeStaticallyReferencedJniMethods_afInet and Java_io_netty_incubator_codec_quic_QuicheNativeStaticallyReferencedJniMethods_afInet__)
                                                                                                    	at io.netty.incubator.codec.quic.QuicheNativeStaticallyReferencedJniMethods.afInet(Native Method)
                                                                                                    	at io.netty.incubator.codec.quic.Quiche.<clinit>(Quiche.java:84)
                                                                                                    	at io.netty.incubator.codec.quic.Quiche.quiche_version(Native Method)
                                                                                                    	at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:43)
```
